token:
  expiration_time: 864000000
  secret: '{cipher}AQCrJj7AfOSktg7SXG0lrzi+S++bUs6/gZ4sWXJK0oZDLBy80zgzACnSlsS1KzPPaNsKkPB87EFCSEMLuDF2uqRsNWS//OreGT5K6rDMZVe4Bp01gz541P1clx0c/yFo+/hAYeDXb55aeRKf1yk2p9v+h5Ei+/ZFt9VSE1Ma2qC809SHKubNyYPGD4L4M/gWAAgrbqNKuKSEy7MI17vxaG+Jwgsl1e3KWXjbh7W5KjAOCY0YvjPlyVOf2m+vBzJUrEyfjn+BHTqKyYEqF1bx8d4wYUcW46p2bSzAcj76cCiQ8/Y8Xi4ap/Q61bNKcoZCAOLq9k81vJoBthI//trtisA9v/G71ODQCfDoIWgyVanyLODYf0yYxSU2zwNbXDIw7RTUhGFGjLxtI8A8l5EU2Qpa'

gateway:
  ip: 0.0.0.0
  